#!/bin/bash

npm install yarn

cd theia
../node_modules/.bin/yarn && \
    ../node_modules/.bin/yarn theia build && \
    rm -rf ./node_modules/electron && \
    ../node_modules/.bin/yarn cache clean
    
